export const BACKEND_CONFIG = {
  SES: {
    VERIFIED_SES_IDENTITY_ARN: "VERIFIED_SES_IDENTITY_ARN",
  },
  SECRETS: {
    STRIPE_API_SECRET_ARN: "STRIPE_API_SECRET_ARN",
    SLACK_FEEDBACK_API_SECRET_ARN: "SLACK_FEEDBACK_API_SECRET_ARN",
  },
  GSI: {
    COGNITO_ATTRIBUTES_EMAIL_GSI: "COGNITO_ATTRIBUTES_EMAIL_GSI",
    USER_DATA_EMAIL_GSI: "USER_DATA_EMAIL_GSI",
    SLACK_USER_ID_GSI: "SLACK_USER_ID_GSI",
    REFERRAL_ID_GSI: "REFERRAL_ID_GSI",
    REFERRAL_COUPON_GSI: "REFERRAL_COUPON_GSI",
    REFERRAL_EMAIL_GSI: "REFERRAL_EMAIL_GSI",
  },
  STRIPE: {
    SIGNING_KEY: "SIGNING_KEY", // dev only
  },
};
